# n1 = int(input('Digite um valor: '))
# n2 = str(input('Digite um valor: '))
# n3 = float(input('Digite um valor: '))
#
# print(f'O type de {n1} é ', type(n1))
# print(f'O type de {n2} é ', type(n2))
# print(f'O type de {n3} é ', type(n3))
n = input('Digite algo: ')
print(f'O tipo primitivo desse valor é ', type(n))
print('Só tem espaços?', n.isspace())
print(f'É um número?', n.isnumeric())
print(f'É alfabético?', n.isalpha())
print(f'É alfanumérico?', n.isalnum())
print(f'Está em maiúsculas?', n.isupper())
print(f'Está em minúsculas?', n.islower())
print(f'Está capitalizada?', n.istitle())
